### ISSUE TITLE
check warns in legit use cases

### ISSUE THREAD

**Issue by Phil-Friderici** [voxpupuli/puppet-lint-undef_in_function-check#3]
when using ```hiera_hash(key, undef)``` the check puts out a warning.
This shouldn't happen as this is a legit use case also described in the docs [1].

[1] https://docs.puppet.com/puppet/latest/reference/function.html#hierahash

**Comment by domcleal** [comment]
This behaviour changes with Puppet 4 using the functions API (i.e. https://docs.puppet.com/puppet/latest/reference/yard/Puppet/Functions.html) so it might be that this lint check should be recommended for Puppet 3 only.  hiera_hash() is a 4.x function written using the new API.

In the new function API, I think undef gets passed through as nil rather than an empty string so it's less likely to be a bug/lint concern than previously. The lint check does still apply for parser functions written using the 3.x API, but it's not going to be possible to differentiate between them.

**Comment by Phil-Friderici** [comment]
@domcleal Thanks for your answer :)
Seems that ```# lint:ignore:undef_in_function``` will become my new friend in these cases.
